version: "3"
services:
  vzy-api:
    image: vzy-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/api
      - /api/node_modules
    container_name: vzy-api
    stdin_open: true

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx configuration file
    ports:
      - "80:80" # Expose Nginx on port 80
    depends_on:
      - vzy-api
